def text():
    print("It is Sunday afternoon, and you have reached the end of your rope.  Your term paper is due first thing tomorrow morning.  If you ever hope to pass with the rest of your friends, you're really going to have to push yourself. Your assignment was to visit the Cragmore Museum of Natural History (which is only five blocks from your home), and do a report on any of their special exhibits. Unfortunantly, your classmates have already taken the best topics.")
    print("")
    print("")
    print("All that is left for you to choose from is:")
    print("")
    print("")
    print("[Life In Ancient Egypt]")
    print("          or ")
    print("[Gems And Minerals Of The World]")
    print("")
    print("")
    print("You are standing in the museum lobby with a notebook and pencil in hand.  It is a beautiful sunny afternoon, and everyone you know is outside enjoying the warm weather.  Hardly anyone is in the museum today.  You wish you weren't either.  But that important paper is due first thing tomorrow morning. Finally you must decide.")
    print("")
    print("")
    print("")
    print("+ If you want to go to the Hall of Ancient Egypt, enter 3.")
    print("")
    print("+ If you want to go to the Hall of Gems and Minerals, enter 4.")
    print("")
    print("")
    return
