def text():
    print("")
    print("")
    #print("[From part 41]")
    print("")
    print("You take the bottle to the head of the museum's archaeology department, Professor Leopold Brown.  A large man, Brown must weigh about three hundred pounds.")
    print("")
    print("He is happy to translate the hieroglyphics for you.  He can't give you an exact translation, but the bottle seems to have been created by an order of ancient magicians.  The bottle seems to have been created by an order of ancient magicians.") 
    print("")
    print(' The bottle says it contains "the elixir of transformation."  Professor Brown returns the bottle to you.  He does not know what to make of it.')
    print("")
    print("Just then the door of the office bursts open, and seven men and women in robes enter.")
    print(' "That bottle is our property," says one of them.  "Please return it at once, or we shall have to take it."')
    print("")
    print("Each person has a golden-handeled knife.  Professor Brown starts to protest.  You are standing next to the back door of the office.")
    print("")
    print("")
    print("+ If you want to run out the back door, enter 13 to continue.")
    print("")
    print("+ If you feel you have to hand over the bottle to the seven people, enter 17 to continue.")
    print("")
    print("") 
    return