def text():
    print("")
    print("")
    #print("[From part 6]")
    print("")
    print("Before you can answer, another voice speaks up from beind you.")
    print('"Officers, this is one of the new pyramid worksers from Mesopotamia.  Come on you lazy rascal, get back to work."')
    print("You turn to see a tall young man dressed in simple clothing.")
    print('"Are you saying this stranger works for you, Calik?" asks one of the men with swords.')
    print('"Yes," says the man.  "Now lets get back to work."')
    print("The three men go away.  you are left alone with the man called Calik.")
    print('"You do not really have to work with us," says Calik with a smale.  "I just did not want you sent to work the galleys."')
    print("But we certainly could use your help.  Building a pyramid is hard work, as you must know.  But we can give you some proper clothing, food, and a place to sleep tonight.")
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return