def text():
    print("")
    print("")
    #print("[From part 13]")
    print("")
    print("You run to the Hall of Dinosaurs. On the way, you pass an office door with a sign that says:")
    print("")
    print("")
    print("[Dr. Margaret Walker]")
    print("[Professor of Pre-History]")
    print("")
    print("[Do Not Disturb]")
    print("")
    print("")
    print("+ If you want to hide in this office, enter 70 to continue.")
    print("")
    print("+ If you want to go on to the Hall of Dinosaurs, enter 74 to continue.")
    print("")
    print("")
    return