def text():
    print("")
    print("")
    #print("[From part 7]")
    print("")
    print("You take the slow geology cruiser and hope for the best.  You fly low over the forests and lakes of Andromeda.  It works.  You pass across the other side of the planet undetected by the Voxons.  After you land, you are led inside the rebel stronghold.  The three of you are introduced to the rebel leader, Alf Gan-Rosh.")
    print('"To defeat Lord Snag, we need the Stone of Narvelin," says Gan-Rosh.  "But the Stone is guarded by the Mangons."')
    print("")
    print('"What are Mangons?" you ask.')
    print('"Monsters with a keen sense of taste and smell," says Gan-Rosh.  "They vaporize anyone they do not like.  We have never known them to like anyone.  We must act fast.  Time is running out for Andromeda."')
    print("")
    print("You, Nisko and vleet discuss the problem.  Vleet reminds you that they have collected many unusual minerals from different worlds.  Perhaps one of them will be useful to you now.  you check the ship's computer.  There are three elements which may help.")
    print("")
    print("")
    print("[Element 40, Zenium - Brings Invisibility]")
    print("")
    print("[Element 50, Meerang - Brings the Force of Lasers]")
    print("")
    print("[Element 53, Argonix - Brings Loss of Odor]")
    print("")
    print("")
    print("+ Enter the element you wish to take with you to continue.")
    print("")
    print("")
    return