def text():
    print("")
    print("")
    #print("[From part 5]")
    print("")
    print("Ignoring the voice, you keep walking down the hall.  As you turn the corner, Voxon guards capture the three of you and throw you into an abandoned storage room (There was never a dungeon built in the Andromedan palace).")
    print("")
    print("Several guards stand outside your door.")
    print("")
    print('"What is going to happen to us?" you whisper.')
    print("")
    print('"If we are lucky," says Vleet, "we may be sent to work in the Mines of Pluto for the rest of our lives."')
    print("")
    print('"... and if we are not lucky?"')
    print("")
    print('Before Vleet can answer, you hear a small scratching noise somwhere in the room.  You freeze.  Then the scratching turns into a small tapping noise.  Tip... Tap, Tap, Tap.  Tip... Tap, Tap, Tap.')
    print("")
    print("")
    print("+ If you want to search the room and try to find what is making the noise, enter 37 to continue.")
    print("")
    print("+ If you want to tell the guards about the noise, enter 34 to continue.")
    print("")
    print("")
    return