def text():
    print("")
    print("")
    #print("[From part 17]")
    print("")
    print("By now the museum has closed.  Most of the lights are turned off.  Together you tiptoe behind the partitions, and see the seven people use heavy iron tools to crack open a newly arrived mummy case.  They pour the liquid from the bottle over the mummy inside.  The mummy comes to life!")
    print("")
    print('"Awake, pharaoh!" says the leader.  "We, the Seven Priests of Amun-Ra, have brought you BACK TO LIFE!!!  With your help, we will control the world!"')
    print("")
    print("The mummy, however, does not seem to want to help these people.  He tries to fight, but he is still too weak after remaining undisturbed for over 3,000 years.")
    print("")
    print("The priests easily tie him up with rope.")
    print("")
    print('"We just need to get him back to the desert," says the leader.  "That will bring him back to his senses.  The helicpoter should be here by now, Hassan.  Take the others and bring our equipment up to the roof.  Then come back and get me and the pharaoh.  I will stay here until you return.  Now, move quickly!"')
    print("")
    print("To stop the Seven Priests of Amun-Ra, you must not let them take away the mummy.")
    print("")
    print("")
    print("+ If you want to send the professors to fetch the museum guards, enter 33 to continue.")
    print("")
    print("+ If you want to think of some way to rescue the mummy yourself, enter 38 to continue.")
    print("")
    print("")
    return