def text():
    print("")
    print("")
    #print("[From part 5]")
    print("")
    print('You walk with care into the dim room.  The door closes quietly behind you.  Now it is completely dark.  "Who is there?" asks Vleet.  Nisko bangs into some metal objects, which clatter to the floor.  "We must be in a kitchen," he reasons.  "This room is full of pots and pans."')
    print("")
    print('"Shh!" says a strange voice.  "Stop that racket.  Do you want Lord Snag himself to find us?"  A small light comes on, and you see a short figure behind a counter.  He introduces himself as Milo Vern, former chief to the Andromedan Royal Family.  "I have been hiding in here since the day Lord Snag took over the palace," he says.')
    print("")
    print('"What has happened to the palace?" asks Vleet.')
    print("")
    print('"Just what he is doing to the rest of our beautiful planet.  He is taking away everything of value - our trees, our minerals, out food, our women, even our water.  Soon there will be nothing left."')
    print("")
    print('"Are there no other loyal Andromedans left in the palace?"')
    print("")
    print('"None but me," says Milo.  "Only the slaves of Lord Snag work here now.  I have a plan to stop Snag, but I need your help.  Will you help me?"  You agree to help.')
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return