def text():
    print("")
    print("")
    #print("[From part 27]")
    print("")
    print('"Today is the birthday of Lord Snag," says Milo, "and I am baking him a cake."')
    print("")
    print('"A poison cake, I hope," says Vleet.')
    print("")
    print('"No," says Milo.  "Snag has his slaves taste the food first.  The cake cannot be poisoned, but it will change Snag forever.  No one will notice until it is too late.  The cake will be ready in a minute.  all we have to do is take it to the main kitchen and replace the real cake with ours."')
    print("")
    print('"There is only one problem wiht this plan," says Nisko.  "Which of us will take the cake into the kitchen?"')
    print("")
    print('"Of course, I would be glad to," says Milo, "but I really do not feel so well.  Would one of you please take it instead?  It is our only chance to save Andromeda."')
    print("")
    print("You, Nisko and Vleet draw straws...")
    print("")
    print("You choose the short one.")
    print("")
    print("")
    print('Proud Milo gives you his cake.  "Go down the hall, take the second door on the right.  Just replace the old cake with this one.  They will look exactly alike.  All the cooks are on their break now, so the kitchen will be empty.  Then just come back here and hide with us.  Here - wear my old chef hat as a convincing disguise, just in case you meet any of the cooks in the hall.  They will think you are one of the slave workers brought here from other worlds.  Now go, before the cooks return."')
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return