def text():
    print("")
    print("")
    #print("[From part 28]")
    print("")
    print('"But what does the cake do?" you ask.  "What is in the recipe?"  Milo urges you to hurry.  He says he will explain as soon as you return.')
    print("")
    print("You take the cake and find the main kitchen.  Sure enough, the room is empty.  Inside, all the food is ready for the feast.  You pick up the old cake - Milo certainly has done a fine job copying it.  - and throw it down the disposal unit.  You put the new cake in its place and run to the door.  Just then the cooks and a squad of guards return.  They are in a panic.")
    print("")
    print('"Spies have been found in the palace," says the head cook.  He looks at you and then says, "Hurry! You carry the cake."')
    print("")
    print('The good news is that no one seems to suspect you are a spy.  The bad news is that you now have to deliver the birthday cake to Lord Snag in person.')
    print("")
    print("In the throne room, a wild birthday celebration is going on.  There is Snag: a giant monster with great green horns and claws.  Shoveling food into his mouth, he never seems to get full.  You hope the cake Milo made works.  You are certainly glad you won't eat it.  Then your heart sinks.  You see Nisko, Vleet and Milo caught in a cage.  For their sake, you pretend you don't know them.  An hour of eating passes, and it's finally time for dessert.")
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return