def text():
    print("")
    print("")
    #print("[From part 20]")
    print("")
    print("")
    print("You don't think you can safely outrun the Voxons, so you crash-land your ship in the thick forest below.  It works.  The Andromedan trees break your fall, and you come to a bumpy, but safe landing.")
    print("")
    print('To your surprise, the Voxons do not follow you.  They turn and fly back to Andromeda Central.  Seeing your confusion, Vleet explains, "Even the Voxons have heard the stories about the Great Forest of Andromeda.  Everyone says it is the most dangerous of places, but no one knows if the stories are true.  No one ever comes here.  Even if we survived the crash, the Voxons must think we wil not get out of the forest alive."')
    print("")
    print("The forest floor is dark.  You can't even see the tops of the trees.  Barely any light from the Andromedan sun, Alpha Centauri, finds its way through the thick leaves.")
    print("")
    print('"What kinds of stories?" you ask.  But before Vleet can answer, you hear a loud roar.')
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return