def text():
    print("")
    print("")
    #print("[From part 23]")
    print("")
    print("")
    print("You follow the tapping sound and finally find its source behind the doors of a low cupboard.  An Andromedan is couched inside.")
    print("")
    print('"Follow me," he says.  The three of you crawl inside the cupboard, close the small door behind you, and begin to follow a dark passageway.  Soon, you come to a small room which looks like an abandoned kitchen.')
    print("")
    print('"My name is Milo Vern," says the Andromedan.  "I have been hiding here since Lord Snag took over.  I do not know why you came to the palace, but it is too dangerous for you here."')
    print("")
    print('"If you want to help defeat Snag, go to the mountains, and go quickly.  Good-bye for now."  He disappears back into the passageway.')
    print("")
    print('"I think going to the mountains is a wonderful idea," says Nisko.')
    print("")
    print('"Let us get out of here!" says Vleet.')
    print("")
    print("+ You lead your two scared geologists safely out of the palace.")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return