def text():
    print("")
    print("")
    #print("[From part 25]")
    print("")
    print("")
    print("There is not time to look for guards.  You have to create some kind of distraction.")
    print("")
    print('"Professor Brown," you whisper.  "Go back to the hallway and make some kind of noise.  Get their leader out of this room.  Do whatever you have to do."')
    print("")
    print('"Leave it to me," says Professor Brown.')
    print("")
    print('Now it is up to you and Professor Karp.  You wait fifteen seconds, then twenty seconds.  The priests will be back any minute to pick up their leader and the mummy.  What happened to Dr. Brown?')
    print("")
    print('Suddenly you hear the noise of a horn.  The leader is alert.  He goes to see what the noise is.  Dr. Karp says, "How clever of Dr. Brown - imagine using the horn of Im-ho-tep."')
    print("")
    print("This is your only chance.  You and Karp run up to the mummy case and untie the mummy.  The mummy is glad to be free.  But now the seven priests return, with Professor Brown as tehir prisoner.")
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return