def text():
    print("")
    print("")
    #print("[From part 43]")
    print("")
    print("")
    print("It is dangerous in the forest, so you stay safe inside your ship.  Realizing no one is going to come and rescue you, you go out and catch some small animals to eat and start a small fire.")
    print("")
    print("As the days pass, you get better at surviving in the forest.  Eventually you befriend the forest people.  Now you are safe in the forest, while around and above you Andromedan rebels fight their last losing battle against Lord Snag and his Voxons.")
    print("")
    print("Sadly, you realize your safety is only temporary.  Sooner or later, the Voxons will turn their attention to the riches of the forest.  You wonder how much time you have left.")
    print("")
    print("")
    print("+ The End.")
    print("")
    print("")
    return