def text():
    print("")
    print("")
    #print("[From part 22]")
    print("")
    print("")
    print('You choose the element Zenium, which makes you invisible.  That helps get you through the forest undetected by wild animals.  But it does not help you with the Mangons.  They smell you from a mile away and come flying out at you.  You run as fast as you can.  However, you cannot out run the Mangons. The first slash, to your back, had enough force to briefly lift you off your feet.  Your breathing becomes more and more labored, your head becomes dizzy.  Your only thought is to simply run... somewhere, anywhere.  You feel the second and third slashes across your shoulder blades.  You feel no pain, only the flowing of sweat rolling down your back.  As you stumble, you instinctively lunge your arms forward to catch yourself.  The Zenium has begin to wear off and you can see the outlines of your hands. As you fall, your back is saturated with blood.  You drift into unconsciousness before your head hits the ground.')
    print("")
    print("")
    print("You awaken.  Your head hurts and you cannot feel anything below your chest, except for a slight tugging from your hips.  You look up, only to see darkness directly infront of you.  The blue sky silhouettes against the darkness.  You feel intense pressure on your chest and the subsequent snapping of ribs as the pressure repositions itself.  You give out a groan. The movement stops.  The darkness remains still.  You lay still, attempting to understand what is happening.  The sickening sound of a pumpkin being hallowed can be heard in the distance, along with gentle breathing.  Not your breathing.  Controlled breathing.  Calm breathing.  You labor to let out another moan.  As if to respond, you feel several feet of wet rope smack against your thighs.  The pressure on your chest, repositions itself, sinking sharp nails into your sternum.  The darkness drifts to your right, relieving much of the pressure on your chest.  As you lay there, scared and confused, it finally comes to you.  You begin to hyperventilate and cannot catch a breath to let out a deceint scream, only a pitiful wimper.  The sharp talons of the Mangons have severed your spinal cord causing you to loose feeling below your chest.  While you were unconscious, the Mangons rolled you onto your back, while taking turns plunging their powerful beaks into your stomach.  After the  fourth attempt, the Mangons yellow beaks are stained dark red.  Your intestines jumbled like loose rope, cover your legs.")
    print("")
    print("")
    print("+ The End.")
    print("")
    print("")
    return