def text():
    print("")
    print("")
    #print("[From part 3]")
    print("")
    print("")
    print("A sky show in the planetarium is being projected against the high round ceiling.  No one in the audience notices you as you take a seat to the rear, with your back to the wall")
    print("")
    print("You take out the bottle from your pocket.  It seems to be made of clay, and you wonder what kind of liquid is inside.  You break open the seal and sniff.  It is a strange, delicious smell.")
    print("")
    print("")
    print("+ If you want to take a sip of the liquid, enter 6 to continue.")
    print("")
    print("+ If you want to take the bottle to the head of the museum's archaeology department, enter 11 to continue.")
    print("")
    print("")
    return