def text():
    print("")
    print("")
    #print("[From part 35]")
    print("")
    print("")
    print("An animal that looks like a lion with antlers leaps through the trees towards you.")
    print("")
    print("You scramble back into your ship.  The animal is smart enough not to attack the metal ship, so it sniffs around and looks for other prey.  Then, to your horror, you notice two small alien children who have come out of the forest to see what has caused the crash.  The antlered lion gets ready to pounce on them.")
    print("")
    print("To save the children, you shoot at the animal with lasers from the ship.  The Andromedan lion flees!  Soon the children's parents arrive, carrying primitive laser guns of their own.  But they do not seem to want to go near your ship.  They wave their thanks to you, then take their children and walk away into the gloom of the forest.")
    print("")
    print("")
    print("+ If you want to follow after them, enter 47 to continue.")
    print("")
    print("+ If you want to stay in the safety of the ship, enter 39 to continue.")
    print("")
    print("")
    return