def text():
    print("")
    print("")
    #print("[From part 30]")
    print("")
    print("")
    print("You try to remember Milo's rushed words:")
    print('"The cake will not be poisoned...  No one will be able to tell the difference until it is too late."  You hope he was right.')
    print("You pick up a piece of cake and take a small bite.  It doesn't taste bad, just a bit spicy.  What will it do to you?")
    print("Your stomach begins to feel warm, your head feels light.  Then you begin to feel better than you ever have in your life.  You even begin to see things more clearly.")
    print('"This is the best cake I have ever had," you say.  Snag is furious.  He grabs the rest of the cake and swallows it whole.  "Hmm," he says.  "That really was good."')
    print('Then he looks confused.  He trembles, vomits and faints.  Lord Snag, holding his throat, grabs this throat and collapses.  Snag is dead.  Unknown to everyone except Milo, Lord Snag is deathly allergic to peanuts.  The cake Milo made, is infused with peanuts and peanut extract.  Everyone is standing in silence, bewildered and confused.  Finally a guard speaks: "Free the prisoners.  Stop the destruction. End this terrible mistake!"')
    print("")
    print("There is rejoicing throughout Alpha Andromeda.  Milo's recipe worked.  The peanut-laced cake caused Lord Snag's throat to swell and cut off his airflow, suffocating him.  Snag's body was drug into the courtyard of the palace, were it was dismembered and burned.")
    print("Nisko and Vleet are proud of your courage.")
    print("The Andromedans present you with rare gems and a ride home.  On the way, Nisko and Vleet help you with your term paper.  They promise to come back to visit you on Earth.  They provide you with a special device so you may visit them on Andromeda whenever you like.")
    print("")
    print("+ The End.")
    print("")
    print("")
    return