def text():
    print("")
    print("")
    #print("[From part 26]")
    print("")
    print("")
    print("You check for the bottle.  Since it brought you here, you don't want to lose it.  It may be your only way to get home again.  The bottle is still safely hidden in your clothing, but where is Calik?  In the distance you see a lone figure walking away from the camp.  You are sure it was Calik.")
    print("")
    print("")
    print("+ If you want to follow him, enter 56 to continue.")
    print("")
    print("+ If you want to remain in camp as you promised, enter 51 to continue.")
    print("")
    print("")
    return