def text():
    print("")
    print("")
    #print("[From part 43]")
    print("")
    print("")
    print("Through the jungle you follow the forest people.  They seem to know when to hide from giant animals and when to walk safely.  After several hours, you find yourself walking in the foothills of some mountains.  Suddenly, the forest people point to what may be the enterance to the cave.  Then they walk back to the forest.  You and Nisco and Vleet cautiously go inside the cave.")
    print("")
    print("The room is full of Andromedans.  You have found the rebel band!  The rebel leader, Alf Gan-Rosh, speaks to you:")
    print('"We are most glad to have you here.  Our spy in Andromeda Central tells us that Lord Snag is growing quite angry with us.  He ordered his troops to raid our villages.  To pass along a message, he beheadded a group of children in front of thier parents!  Our attacks against his mining operations are slowing him down.  Now he is massing a huge force against us.  He does not know where this cave is, but it will not take long."')
    print("")
    print("An explosion rips against the side of the mountain.  Evidently Lord Snag has already begun his attack.  You cannot stay trapped in the cave.  You must go outside.  But where?")
    print("")
    print("+ If you want to advise the rebels to go higher into the hills, enter 82 to continue.")
    print("")
    print("+ If you want to advise the rebels to go down to the forest, enter 88 to continue.")
    print("")
    print("")
    return