def text():
    print("")
    print("")
    #print("[From part 45]")
    print("")
    print("")
    print("You fall back into an uneasy sleep.  When you awake, Calik is back on his bed as if he never left.  You say nothing to him during the day.  But after the sun sets, you take him aside and tell how you saw him leave last night.")
    print("")
    print('Calik merely laughs. "I did not go anywhere," he says.  "am I not the one who told YOU not to leave at night?  Are you sure you were not dreaming?"')
    print("")
    print("You know you were not dreaming.  Why is Calik not telling you the truth?")
    print("")
    print("")   
    print("+ If you want to wait to see if Calik wil leave again, enter 63 to continue.")
    print("")
    print("+ If you want to take a new sip of the liquid, enter 85 to continue.")
    print("")
    print("")
    return