def text():
    print("")
    print("")
    #print("[From part 69]")
    print("")
    print("")
    print("You follow Calik through the dark streets of the nearby village, careful that he does not see you.  Soon you lose sight of him.  Did he know you were following?")
    print("")
    print("You are not sure where you are.  One street looks like the next.  Suddenly a woman in a white robe stands in your path.")
    print("")
    print('"I have noticed you since your arrival here," she says.  "May I have a word with you?"  Your heart begins to flutter, and your breathing increases.  Nervously, you nod your head up and down unaware you look like an idiot.  You have seen several films on late night TV that start out this way...  As far as you know, you will wind up drugged and laying in a bathtub full of ice with your kidney removed.  But at this moment, that is the least on your mind.')
    print("")
    print("")   
    print('"I am one of the Servants of Amun-Ra.  Several months ago, we lost a small object, a bottle to be precise."')
    print("")
    print("Rats... too good to be true...")
    print("")
    print('"Please do not ask me how, but I believe you may know something about it.  The information you may have is very important.  It could save many lives.  I am prepared to offer you gold if you can help me.  Are you interested in my offer?"')
    print("")
    print("")
    print("+ If you are interested, enter 64 to continue.")
    print("")
    print("+ If you would like to say you don't know anything about the bottle, enter 60 to continue.")
    print("")
    print("")
    return