def text():
    print("")
    print("")
    #print("[From part 65]")
    print("")
    print("")
    print("Could the bottle you have be the same one wanted by the Priests of Amun-Ra?")
    print("")
    print("You would like to help Calik, but you don't want to give him your only possible way of getting home.  You hope the answer will come to you tomorrow.  But all that comes to you as you walk back to camp are the Priests of Amun-Ra.  They sneak up on you from behind.  You feel a sudden hit to the back of the head and plunge into darkness.")
    print("")
    print("You awake to the morning sun gently shining on your face and a splitting headache to the back of your head.  Small, gentle beads of sweat begin to collect around your cheeks and forehead, as the morning sun gets stronger.  Laying stretched out on the sand, you know today will be hot.  As you sit up, it finally occurrs to you why you were there.  The priests attacked you last night, knocked you out, and left you in the desert alone.  Without thought, your hands instintively begin drifting over your pockets searching for the bottle.")
    print("")
    print("Gone.  It's gone.")
    print("")
    print("You stand up, scanning the horizon for anything.  Nothing.  Nothing but sky meeting the desert sand... and that sun, overhead, growing hotter and hotter.")
    print("")
    print("")
    print("+ The End.")
    print("")
    print("")
    return