def text():
    print("")
    print("")
    #print("[From part 41]")
    print("")
    print("")
    print("The liquid smells so good that you take just a tiny sip.  It tastes wonderful, too, like honey and cinnamon.  You take another sip.  The planetarium speaker is saying something about the night sky in August, but the voice sounds like it is coming from underwater.  You hear a gentle hum.  Then all grows dark around you.")
    print("")
    print("The next thing you see is a camel, walking across the desert.  you are sitting beneath a palm tree.  It is very early in the morning, and the sun is just about to rise.  But all around you, men, women, and children are walking to a marketplace.  A huge pyramid is under construction nearby.")
    print("")
    print("The words you hear are a foreign language, yet you can somehow understand every word.  you pinch yourself, but you are not dreaming.  The liquid must have carried you back in time to the land of ancient Egypt!")
    print("")
    print('Suddenly three men with swords and golden armbands walk up to you and ask, "Who are you, and why are you wearing such a strange costume?  Answer well, or we will send you to the galleys."')
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return
    