def text():
    print("")
    print("")
    #print("[From part 56]")
    print("")
    print("")
    print('"I am sorry," you tell her.  "But I do not know anything about such a bottle."')
    print("")
    print('Her eyes flash, but her voice is still warm and soothing. "Are you sure?" she asks?')
    print("")
    print("Suddenly Calik appears, walking down the street towards you.  You call his name, and the woman diappears into an alley.")
    print("")
    print('Calik hurries over to you.  "Are you alright?" he asks "What did that woman want, and why did you leave camp?"')
    print("")
    print("")
    print("+ If you want to tell Calik what the woman said, enter 65 to continue.")
    print("")
    print("+ If you want to say nothing for now, enter 67 to continue.")
    print("")
    print("")
    return