def text():
    print("")
    print("")
    #print("[From part 56]")
    print("")
    print("")
    print("You follow the servant around to the back of the palace.  He is bringing the pharaoh some fresh dates just picked for the royal breakfast.  You offer the serveant the ring on your finger and you say you only want to serve the pharoah his dates.  You speak the language so well, and your ring is so shiny, that the servant is delighted to let you do his work today.")
    print("")
    print("You enter the palace.  You have never seen any building so splendid.  The beautiful columns, plants, pools, and painted walls sparkle.  Then you see a man alone by a pool.  From his clothing, you know this can only be the pharaoh.")
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return