def text():
    print("")
    print("")
    #print("[From part 51 or part 71]")
    print("")
    print("You decide that if Calik leaves tonight, you'll follow him.  When the moon is above the pyramid, Calik slips away again.  You follow him in secret to a grove of palm trees.  You climb one of the trees to watch and listen.  Other men and women are gathering below.")
    print("")
    print('Calik speaks: "We know the Priests of Amun-Ra are ready.  Why are they waiting?  I believe they still like the one thing which will guarantee their victory:  the potion of Thebes."')
    print("")
    print('"We do not know who stole the potion from the magicians.  But I do not need to tell you that if the portion falls into the hands of the Priests, they will gain control over all the Nile Valley and begin a rule of madness and evil."')
    print("")
    print('"Now time is running out.  They will make their move soon, with or without the potion.  Tomorrow, we must find the potion before the Priests do."')
    print("")
    print("There are no questions.  Everyone leaves the grove except Calik, who remains deep in thought.")
    print("")
    print("")
    print("+ If you want to approach Calik and tell him about the bottle you found, enter 78 to continue.")
    print("")
    print("+ If you do not want to tell Calik, enter 59 to continue.")
    print("")
    print("")
    return