def text():
    print("")
    print("")
    #print("[From part 60]")
    print("")
    print('"I will tell you," you say, "but not here.  Can we walk back to the camp?"')
    print("")
    print('On the way back, you apologize to Calik for leaving the camp.  But you also remind him that he left camp too.  Calik has a laugh at this.  Then you tell him what happened with the woman.')
    print("")
    print('"I am glad I arrived when I did," says Calik.  "That woman was no servant.  She is a Priest of Amun-Ra.  All I can tell you about them is this: A magicians potion was stolen reciently from the pharoas place.  No one knows exactly what the potion can do, and the magicians are not saying."')
    print("")
    print('"The Priests of Amun-Ra want to get this potion before the pharaoh does, and that would be a dark day for all of us.  Please go back to camp as quickly as possible."  With that, Calik walks away.')
    print("")
    print("")
    print("+ If you want to go after Calik and tell him about the bottle you have, enter 78 to continue.")
    print("")
    print("+ If you do not want to tell Calik, enter 59 to continue")
    print("")
    print("+ If you want to go find a private place to take a drink from the bottle, enter 85 to continue.")
    print("")
    print("")
    return