def text():
    print("")
    print("")
    #print("[From part 16]")
    print("")
    print('All you can think to say is, "You are welcome.".')
    print("")
    print('"But now what is to become of me?" asks the ape.')
    print("")
    print('"Where will I go to live?  No museum wants a live gorilla.  Especially, a live, TALKING gorilla.  I will be sent to a labatory to be dissected."')
    print("")
    print("Just then, Professor Brown shows up.  He is glad to see you unharmed, but he is quite surprised to see a live gorilla.")
    print("")
    print('"Do not worry professor," you say.  You tell him exactly what happened.  "Can you help me?" the gorilla asks Professor Brown.  "I used to live in Africa."')
    print("")
    print('"You could always live in Metropolitan Zoo," you suggest.  You want to help the gorilla find a good home, but you are afraid a museum watchman is goin gto stroll by any second.')
    print("")
    print('Then Professor Brown says, "You know, I am about to leave for a new digging expedition in Africa.  You could come along with me on the ship.  We could disguise you in some of my old clothing."')
    print('"I do not know," says the gorilla.  he looks at you and asks, "What do you think?"')
    print("")
    print("")
    print("+ If you want to help the professor take the gorilla to the pier, enter 49 to continue")
    print("")
    print("+ If you want to take the gorilla to the zoo by subway, enter 55 to continue.")
    print("")
    print("")
    return