def text():
    print("")
    print("")
    #print("[From part 10 / From part 37]")
    print("")
    print("")
    print("You will go to the mountains for help.  But how do you get there?  You could take the same geology cruiser that brought you to Andromeda.  But the cruiser is slow traveling in the planet's atmosphere.  It would take a full hour.  You could steal a Voxon sprint ship, which would get to the other side of the planet in minutes.")
    print("")
    print("")
    print("+ If you want to take the geology cruiser, enter 22 to continue.")
    print("")
    print("+ If you want to steal a Voxon sprint ship, enter 20 to continue.")
    print("")
    print("")
    return