def text():
    print("")
    print("")
    #print("[From part 21]")
    print("")
    print("You slip inside Dr. Walker's office and lock the door behind you.  The floor is cluttered.  Every shelf and desk is piled high with scientific journals, dinosaur fossils and machine parts.  Giant ferns unlike any you have ever seen grow under purple lights.")
    print("")
    print("Suddenly a strange machine with two lights and two seats materializes in front of you.  On one seat is an open notebook.  The last date in it reads 33,005 B.C.  Could this be a time machine?")
    print("")
    print("That is all you have time to read. You hear a pounding on the locked office door.  You look around and see that this office also has a back door.  The time machine looks simple enough to operate.")
    print("")
    print("")
    print("+ If you want to try to escape by traveling through time, enter 86 to continue")
    print("")
    print("+ If you want to to try to escape through the back door, enter 84 to continue.")
    print("")
    print("")
    return