def text():
    print("")
    print("")
    #print("[From part 81]")
    print("")
    print("You arrive at the palace just after dawn.  When you get to the front of the building, there are dozens of people trying to get in to see the pharaoh.  They form a line outside the palace doors.")
    print("")
    print("You tell a guard that you absolutely must get in first.  But he just frowns and tells you to go to the end of the line.  You see a servent with a breakfast tray going around a corner to the back of the palace.")
    print("")
    print('A man with a beard comes up to you and says, "It may take all day to get in to see the pharaoh today.  You may never get in at all."  Then he whispers, "I have a connection inside the palace.  If you give me that ring on your finger, I will see to it that your message gets to the pharaoh immediately."')
    print("")
    print("+ If you want to follow the servant with the tray, enter 61 to continue.")
    print("")
    print("+ If you want to give this man your ring, enter 73 to continue.")
    print("")
    print("+ If you want to wait your turn in line, enter 77 to continue.")
    print("")
    print("")
    return