def text():
    print("")
    print("")
    #print("From part 74")
    print("")
    print("You drink the entire contents in one gulp, and the clay bottle crashes to your feet.  The seven people gasp.  You feel cold, then warm.  You see the dinosaur skeleton split into crystals of colored light.")
    print("")
    print("The next thing you know, you wake up in a hot world.  Large insects buzz overhead.  You see a huge dinosaur - a triceratops - walking nearby.  Another dinosaur plods along the marsh.  You must have just traveled back in time millions of years!  The potion is gone and you have no way of returning home.")
    print("")
    print("Suddenly a red light streaks overhead and crashes a mile away.  You run there as fast as you can.  You can't believe what you find: an alien spaceship.  Bu tyou are not the first one to find it.  The crash has attracted several hungry dinosaurs.    Two helpless aliens have managed to escape from their craft.  They are in danger of being eaten... so are you.")
    print("")
    print("")
    print("+ If you want to try to save the aliens, enter 94 to continue.")
    print("")
    print("+ If you want to run to safety, enter 97 to continue.")
    print("")
    print("")
    return