def text():
    print("")
    print("")
    #print("[From part 4]")
    print("")
    print("")
    print('"Sorriest appologies!" one alien whispers to you.')
    print("")
    print('"Please help us," asks the second.')
    print("")
    print("You feel sorry for them and decide to help them.")
    print("")
    print('"We are Nisko and Vleet, two geologists.  Your scientists would call our planet Alpha Andromeda, in the Alpha Centauri system.  We did not mean to land on your planet, but our ship ran out of fuel.  This rock contains the element we need to power our ship home."')
    print("")
    print("You lead them safely out of the museum through a service enterance.  Their ship is parked behind some tall bushes in the back.")
    print("")
    print('"Thank you," says Nisko.  "May we show you our planet?  We could bring you back by tonight."')
    print("")
    print("As geologists, Nisko and Vleet could teach you plenty about gems and minerals.  Visiting another planet is something you've always wanted to.")
    print("")
    print("")
    print("+ Press Enter to continue.")
    print("")
    print("")
    return