def text():
    print("")
    print("")
    #print("From part 38")
    print("")
    print('"We have never met a meddler like you," their leader says to you.  "Now we will make sure you never get in our way again..."')
    print("")
    print("Just then, the freed mummy shakes his fists.  He knocks out one priest, then another.  You and the professor tie them up.  Now you can call the police.")
    print("")
    print('"I am greatful to you three brave warriors for your heroism," says the mummy in ancient Egyptian.  "I only wish that I could now go back to the land of my ancestors.  Is there any way that you can help me?  I am already in your debt."')
    print("")
    print("Dr. Brown translates for you, then replies in the same language")
    print('"Yes.  I think we can help you.  Tonight Dr. Karp and I are leaving on a tramp steamer.  We are going on a new dig in North Africa.  We can take you along."')
    print("")
    print("You help the mummy back into his case.  Then you all drive down ot the pier in Dr. Brown's station wagon.  Before the mummy case is loaded on the boat, the ancient pharaoh thanks you.")
    print('"May the gentle winds of Thebes always blow against your back," he says.  Then Dr. Brown closes the case.  The longshoremen think it is just another artifact.  You take a taxi home, full of ideas for your report on ancient Egypt.')    
    print("")
    print("")
    print("+ The End")
    print("")
    print("+ P.S. You got an A.")
    print("")
    print("")
    return