def text():
    print("")
    print("")
    #print("From part 89")
    print("")
    print("You throw stones and sticks to destract the dinosaurs from the aliens.  Your plan works.  The dinsaurs go away.  After the animals have left, you approach the aliens.")
    print("")
    print('"Thank you, Earthling," they say.  "But we are dying anyway."')
    print("")
    print('"No, you are not.  Not if I can help it," you say.  You rush to get them water.  Your quick thinking saves their lives')
    print("")
    print('Now they can begin to rebuild their spacecraft.  "We are from the twenty-third century," they explain.  To thank you, they bring you back to your won time, to your own home.')
    print("")
    print("In their time travels, the aliens have been to ancient Rome, Greece, and Egypt.  Tonight, in your room, they happily tell you everything they discovered about these civilizations.  By morning you are ready to hand in a wondertful term paper.  You can't wait till their next visit.  They have promised to take you along on their next trip.")
    print("")
    print("")
    print("+ The End")
    print("")
    print("")
    return