def text():
    print("")
    print("")
    #print("From part 76")
    print("")
    print("You try lifting the frozen Dr. Walker, To your surprise, she is light as a mushroom.  You quickly carry her away down the hill.  The aliens do not follow you.")
    print("")
    print("You bring Dr. Walker down to the cafe of the prehistoric people you met earlier.  They seem to know Dr. Walker.  Soon she thaws out and feels much better.  She calls the cave people by name and is delighted to meet you.")
    print("")
    print('"Thank you for being so clever in finding me," she says.  "I programmed my time machine to return to the Cragmore Museum should aything happen to me."')
    print("")
    print('Now you tell her the bad news.  "A mammoth broke the time machine."')
    print("")
    print("With the prehistoric people, you all go have a look at it.")
    print("")
    print('"Do not worry," says Dr. Walker.  "We can fix this.  But first, how about some dinner?"')
    print("")
    print("You have to agree, you haven't felt this hungry in ages.")    
    print("")
    print("")
    print("+ The End")
    print("")
    print("")
    return