def text():
    print("")
    print("")
    #print("From part 61")
    print("")
    print("Before the pharaoh has a chance to speak, you blurt out your story and present him with the potion.")
    print("")
    print('"Thank you," says the pharaoh.  "I do not know who you are, but I am in your debt.  Now I have the power I need to defeat the evil Priests of Amun-Ra.  How can I repay you?"')
    print("")
    print('You tell him that you only want to get back to your own time.  He sends you to his magicians, and they help you.  You only ask for one more thing before you return.  You ask the pharaoh for some general information about his country.  After all, you still have to hand in a term paper when you get back.')
    print("")
    print('The pharaoh smiles and gives you a personal tour of his city.  Then he gives you a special present before you return home.')
    print("")
    print("You get a good grade on your term paper, but your parents will always wonder where you got the small gold statue of an eagle.")
    print("")
    print("")
    print("+ The End")
    print("")
    print("")
    return